# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'full_ui_new.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1100, 850)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(10, 10, 1081, 821))
        self.stackedWidget.setObjectName("stackedWidget")
        self.searchPage = QtWidgets.QWidget()
        self.searchPage.setObjectName("searchPage")
        self.tableWidget = QtWidgets.QTableWidget(self.searchPage)
        self.tableWidget.setGeometry(QtCore.QRect(210, 40, 861, 781))
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setTextElideMode(QtCore.Qt.ElideLeft)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setObjectName("tableWidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.searchPage)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 40, 171, 771))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.searchCol_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.searchCol_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.searchCol_3.setContentsMargins(0, 0, 0, 0)
        self.searchCol_3.setSpacing(0)
        self.searchCol_3.setObjectName("searchCol_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.deptLabel_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.deptLabel_3.setObjectName("deptLabel_3")
        self.verticalLayout_11.addWidget(self.deptLabel_3)
        self.deptLineEdit_3 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.deptLineEdit_3.setObjectName("deptLineEdit_3")
        self.verticalLayout_11.addWidget(self.deptLineEdit_3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_11)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.courseNumLabel_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.courseNumLabel_3.setObjectName("courseNumLabel_3")
        self.verticalLayout_13.addWidget(self.courseNumLabel_3)
        self.courseNumLineEdit_3 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.courseNumLineEdit_3.setObjectName("courseNumLineEdit_3")
        self.verticalLayout_13.addWidget(self.courseNumLineEdit_3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_13)
        self.searchCol_3.addLayout(self.horizontalLayout_2)
        self.courseNameLabel_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.courseNameLabel_3.setObjectName("courseNameLabel_3")
        self.searchCol_3.addWidget(self.courseNameLabel_3)
        self.courseNameLineEdit_3 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.courseNameLineEdit_3.setObjectName("courseNameLineEdit_3")
        self.searchCol_3.addWidget(self.courseNameLineEdit_3)
        self.instructorLabel_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.instructorLabel_3.setObjectName("instructorLabel_3")
        self.searchCol_3.addWidget(self.instructorLabel_3)
        self.instructorLineEdit_3 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.instructorLineEdit_3.setObjectName("instructorLineEdit_3")
        self.searchCol_3.addWidget(self.instructorLineEdit_3)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.monCheck = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.monCheck.setObjectName("monCheck")
        self.verticalLayout_4.addWidget(self.monCheck)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.monTimeS = QtWidgets.QTimeEdit(self.verticalLayoutWidget)
        self.monTimeS.setObjectName("monTimeS")
        self.horizontalLayout_3.addWidget(self.monTimeS)
        self.monTimeE = QtWidgets.QTimeEdit(self.verticalLayoutWidget)
        self.monTimeE.setObjectName("monTimeE")
        self.horizontalLayout_3.addWidget(self.monTimeE)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout_10.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tueCheck = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.tueCheck.setObjectName("tueCheck")
        self.verticalLayout_5.addWidget(self.tueCheck)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.tueTimeS = QtWidgets.QTimeEdit(self.verticalLayoutWidget)
        self.tueTimeS.setObjectName("tueTimeS")
        self.horizontalLayout_4.addWidget(self.tueTimeS)
        self.tueTimeE = QtWidgets.QTimeEdit(self.verticalLayoutWidget)
        self.tueTimeE.setObjectName("tueTimeE")
        self.horizontalLayout_4.addWidget(self.tueTimeE)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.verticalLayout_10.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.wedCheck = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.wedCheck.setObjectName("wedCheck")
        self.verticalLayout_6.addWidget(self.wedCheck)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.wedTimeS = QtWidgets.QTimeEdit(self.verticalLayoutWidget)
        self.wedTimeS.setObjectName("wedTimeS")
        self.horizontalLayout_5.addWidget(self.wedTimeS)
        self.wedTimeE = QtWidgets.QTimeEdit(self.verticalLayoutWidget)
        self.wedTimeE.setObjectName("wedTimeE")
        self.horizontalLayout_5.addWidget(self.wedTimeE)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.verticalLayout_10.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.thurCheck = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.thurCheck.setObjectName("thurCheck")
        self.verticalLayout_7.addWidget(self.thurCheck)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.thurTimeS = QtWidgets.QTimeEdit(self.verticalLayoutWidget)
        self.thurTimeS.setObjectName("thurTimeS")
        self.horizontalLayout_6.addWidget(self.thurTimeS)
        self.thuTimeE = QtWidgets.QTimeEdit(self.verticalLayoutWidget)
        self.thuTimeE.setObjectName("thuTimeE")
        self.horizontalLayout_6.addWidget(self.thuTimeE)
        self.verticalLayout_7.addLayout(self.horizontalLayout_6)
        self.verticalLayout_10.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.friCheck = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.friCheck.setObjectName("friCheck")
        self.verticalLayout_8.addWidget(self.friCheck)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.friTimeS = QtWidgets.QTimeEdit(self.verticalLayoutWidget)
        self.friTimeS.setObjectName("friTimeS")
        self.horizontalLayout_10.addWidget(self.friTimeS)
        self.friTimeE = QtWidgets.QTimeEdit(self.verticalLayoutWidget)
        self.friTimeE.setObjectName("friTimeE")
        self.horizontalLayout_10.addWidget(self.friTimeE)
        self.verticalLayout_8.addLayout(self.horizontalLayout_10)
        self.verticalLayout_10.addLayout(self.verticalLayout_8)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.satCheck = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.satCheck.setObjectName("satCheck")
        self.verticalLayout_9.addWidget(self.satCheck)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.satTimeS = QtWidgets.QTimeEdit(self.verticalLayoutWidget)
        self.satTimeS.setObjectName("satTimeS")
        self.horizontalLayout_11.addWidget(self.satTimeS)
        self.satTimeE = QtWidgets.QTimeEdit(self.verticalLayoutWidget)
        self.satTimeE.setObjectName("satTimeE")
        self.horizontalLayout_11.addWidget(self.satTimeE)
        self.verticalLayout_9.addLayout(self.horizontalLayout_11)
        self.verticalLayout_10.addLayout(self.verticalLayout_9)
        self.searchCol_3.addLayout(self.verticalLayout_10)
        self.courseTypeLabel_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.courseTypeLabel_3.setObjectName("courseTypeLabel_3")
        self.searchCol_3.addWidget(self.courseTypeLabel_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.dayCheckbox_3 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.dayCheckbox_3.setObjectName("dayCheckbox_3")
        self.verticalLayout_12.addWidget(self.dayCheckbox_3)
        self.eveningCheckbox_3 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.eveningCheckbox_3.setObjectName("eveningCheckbox_3")
        self.verticalLayout_12.addWidget(self.eveningCheckbox_3)
        self.onlineCheckbox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.onlineCheckbox.setObjectName("onlineCheckbox")
        self.verticalLayout_12.addWidget(self.onlineCheckbox)
        self.horizontalLayout.addLayout(self.verticalLayout_12)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.slCheckbox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.slCheckbox.setObjectName("slCheckbox")
        self.verticalLayout.addWidget(self.slCheckbox)
        self.stabroadCheckbox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.stabroadCheckbox.setObjectName("stabroadCheckbox")
        self.verticalLayout.addWidget(self.stabroadCheckbox)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.searchCol_3.addLayout(self.horizontalLayout)
        self.creditsLabel_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.creditsLabel_3.setObjectName("creditsLabel_3")
        self.searchCol_3.addWidget(self.creditsLabel_3)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.maxCredits_3 = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.maxCredits_3.setObjectName("maxCredits_3")
        self.horizontalLayout_8.addWidget(self.maxCredits_3)
        self.minCredits_3 = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.minCredits_3.setObjectName("minCredits_3")
        self.horizontalLayout_8.addWidget(self.minCredits_3)
        self.searchCol_3.addLayout(self.horizontalLayout_8)
        self.courseLevelLabel_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.courseLevelLabel_3.setObjectName("courseLevelLabel_3")
        self.searchCol_3.addWidget(self.courseLevelLabel_3)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.level100_3 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.level100_3.setObjectName("level100_3")
        self.verticalLayout_15.addWidget(self.level100_3)
        self.level200_3 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.level200_3.setObjectName("level200_3")
        self.verticalLayout_15.addWidget(self.level200_3)
        self.level300_3 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.level300_3.setObjectName("level300_3")
        self.verticalLayout_15.addWidget(self.level300_3)
        self.level400_3 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.level400_3.setObjectName("level400_3")
        self.verticalLayout_15.addWidget(self.level400_3)
        self.horizontalLayout_9.addLayout(self.verticalLayout_15)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.level500_3 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.level500_3.setObjectName("level500_3")
        self.verticalLayout_16.addWidget(self.level500_3)
        self.level600_3 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.level600_3.setObjectName("level600_3")
        self.verticalLayout_16.addWidget(self.level600_3)
        self.level700_3 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.level700_3.setObjectName("level700_3")
        self.verticalLayout_16.addWidget(self.level700_3)
        self.horizontalLayout_9.addLayout(self.verticalLayout_16)
        self.searchCol_3.addLayout(self.horizontalLayout_9)
        self.backButton = QtWidgets.QPushButton(self.searchPage)
        self.backButton.setGeometry(QtCore.QRect(970, 0, 101, 31))
        self.backButton.setObjectName("backButton")
        self.picklesButton = QtWidgets.QPushButton(self.searchPage)
        self.picklesButton.setGeometry(QtCore.QRect(10, 0, 111, 31))
        self.picklesButton.setObjectName("picklesButton")
        self.stackedWidget.addWidget(self.searchPage)
        self.schedulePage = QtWidgets.QWidget()
        self.schedulePage.setObjectName("schedulePage")
        self.backButton_2 = QtWidgets.QPushButton(self.schedulePage)
        self.backButton_2.setGeometry(QtCore.QRect(970, 10, 101, 31))
        self.backButton_2.setObjectName("backButton_2")
        self.picklesButton_2 = QtWidgets.QPushButton(self.schedulePage)
        self.picklesButton_2.setGeometry(QtCore.QRect(20, 10, 111, 31))
        self.picklesButton_2.setObjectName("picklesButton_2")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.schedulePage)
        self.tableWidget_2.setGeometry(QtCore.QRect(180, 70, 891, 741))
        self.tableWidget_2.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(0)
        self.label_5 = QtWidgets.QLabel(self.schedulePage)
        self.label_5.setGeometry(QtCore.QRect(190, 50, 111, 16))
        self.label_5.setObjectName("label_5")
        self.layoutWidget = QtWidgets.QWidget(self.schedulePage)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 80, 141, 461))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.classesBox = QtWidgets.QTextEdit(self.layoutWidget)
        self.classesBox.setObjectName("classesBox")
        self.verticalLayout_3.addWidget(self.classesBox)
        self.findSchedules = QtWidgets.QPushButton(self.layoutWidget)
        self.findSchedules.setObjectName("findSchedules")
        self.verticalLayout_3.addWidget(self.findSchedules)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.allButt = QtWidgets.QRadioButton(self.layoutWidget)
        self.allButt.setObjectName("allButt")
        self.verticalLayout_2.addWidget(self.allButt)
        self.earliestButt = QtWidgets.QRadioButton(self.layoutWidget)
        self.earliestButt.setObjectName("earliestButt")
        self.verticalLayout_2.addWidget(self.earliestButt)
        self.earliestStartButt = QtWidgets.QRadioButton(self.layoutWidget)
        self.earliestStartButt.setObjectName("earliestStartButt")
        self.verticalLayout_2.addWidget(self.earliestStartButt)
        self.latestButt = QtWidgets.QRadioButton(self.layoutWidget)
        self.latestButt.setObjectName("latestButt")
        self.verticalLayout_2.addWidget(self.latestButt)
        self.latestStartButt = QtWidgets.QRadioButton(self.layoutWidget)
        self.latestStartButt.setObjectName("latestStartButt")
        self.verticalLayout_2.addWidget(self.latestStartButt)
        self.shortestDayButt = QtWidgets.QRadioButton(self.layoutWidget)
        self.shortestDayButt.setObjectName("shortestDayButt")
        self.verticalLayout_2.addWidget(self.shortestDayButt)
        self.gapsButt = QtWidgets.QRadioButton(self.layoutWidget)
        self.gapsButt.setObjectName("gapsButt")
        self.verticalLayout_2.addWidget(self.gapsButt)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.cannotFindLabel = QtWidgets.QLabel(self.layoutWidget)
        self.cannotFindLabel.setObjectName("cannotFindLabel")
        self.verticalLayout_3.addWidget(self.cannotFindLabel)
        self.stackedWidget.addWidget(self.schedulePage)
        self.startPage = QtWidgets.QWidget()
        self.startPage.setObjectName("startPage")
        self.advancedSearchButton = QtWidgets.QPushButton(self.startPage)
        self.advancedSearchButton.setGeometry(QtCore.QRect(28, 90, 141, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.advancedSearchButton.sizePolicy().hasHeightForWidth())
        self.advancedSearchButton.setSizePolicy(sizePolicy)
        self.advancedSearchButton.setMinimumSize(QtCore.QSize(120, 50))
        self.advancedSearchButton.setMaximumSize(QtCore.QSize(150, 50))
        self.advancedSearchButton.setObjectName("advancedSearchButton")
        self.scheduleMakerButton = QtWidgets.QPushButton(self.startPage)
        self.scheduleMakerButton.setGeometry(QtCore.QRect(180, 90, 150, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scheduleMakerButton.sizePolicy().hasHeightForWidth())
        self.scheduleMakerButton.setSizePolicy(sizePolicy)
        self.scheduleMakerButton.setMinimumSize(QtCore.QSize(120, 50))
        self.scheduleMakerButton.setMaximumSize(QtCore.QSize(150, 50))
        self.scheduleMakerButton.setObjectName("scheduleMakerButton")
        self.label = QtWidgets.QLabel(self.startPage)
        self.label.setGeometry(QtCore.QRect(70, 10, 201, 71))
        self.label.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label.setObjectName("label")
        self.stackedWidget.addWidget(self.startPage)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        self.advancedSearchButton.clicked.connect(MainWindow.show)
        self.advancedSearchButton.clicked.connect(self.stackedWidget.show)
        self.scheduleMakerButton.clicked.connect(MainWindow.show)
        self.scheduleMakerButton.clicked.connect(self.stackedWidget.show)
        self.backButton.clicked.connect(MainWindow.show)
        self.backButton.clicked.connect(self.stackedWidget.show)
        self.backButton_2.clicked.connect(MainWindow.show)
        self.backButton_2.clicked.connect(self.stackedWidget.show)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tableWidget.setSortingEnabled(True)
        self.deptLabel_3.setText(_translate("MainWindow", "Dept."))
        self.courseNumLabel_3.setText(_translate("MainWindow", "Course Num."))
        self.courseNameLabel_3.setText(_translate("MainWindow", "Course Name"))
        self.instructorLabel_3.setText(_translate("MainWindow", "Instructor"))
        self.monCheck.setText(_translate("MainWindow", "Monday (start-end)"))
        self.tueCheck.setText(_translate("MainWindow", "Tuesday (start-end)"))
        self.wedCheck.setText(_translate("MainWindow", "Wednesday (start-end)"))
        self.thurCheck.setText(_translate("MainWindow", "Thursday (start-end)"))
        self.friCheck.setText(_translate("MainWindow", "Friday (start-end)"))
        self.satCheck.setText(_translate("MainWindow", "Saturday (start-end)"))
        self.courseTypeLabel_3.setText(_translate("MainWindow", "Type"))
        self.dayCheckbox_3.setText(_translate("MainWindow", "DAY"))
        self.eveningCheckbox_3.setText(_translate("MainWindow", "EVENING"))
        self.onlineCheckbox.setText(_translate("MainWindow", "ONLINE"))
        self.slCheckbox.setText(_translate("MainWindow", "SALT LAKE"))
        self.stabroadCheckbox.setText(_translate("MainWindow", "ST ABROAD"))
        self.creditsLabel_3.setText(_translate("MainWindow", "Credits (Max - Min)"))
        self.courseLevelLabel_3.setText(_translate("MainWindow", "Course Level"))
        self.level100_3.setText(_translate("MainWindow", "100"))
        self.level200_3.setText(_translate("MainWindow", "200"))
        self.level300_3.setText(_translate("MainWindow", "300"))
        self.level400_3.setText(_translate("MainWindow", "400"))
        self.level500_3.setText(_translate("MainWindow", "500"))
        self.level600_3.setText(_translate("MainWindow", "600"))
        self.level700_3.setText(_translate("MainWindow", "700"))
        self.backButton.setText(_translate("MainWindow", "Back"))
        self.picklesButton.setText(_translate("MainWindow", "Choose Semester"))
        self.backButton_2.setText(_translate("MainWindow", "Back"))
        self.picklesButton_2.setText(_translate("MainWindow", "Choose Semester"))
        self.tableWidget_2.setSortingEnabled(False)
        self.label_5.setText(_translate("MainWindow", "Possible Schedules:"))
        self.label_2.setText(_translate("MainWindow", "Enter classes here:"))
        self.findSchedules.setText(_translate("MainWindow", "Find Schedules"))
        self.label_4.setText(_translate("MainWindow", "Optimization"))
        self.allButt.setText(_translate("MainWindow", "All"))
        self.earliestButt.setText(_translate("MainWindow", "Earliest"))
        self.earliestStartButt.setText(_translate("MainWindow", "Earliest Start"))
        self.latestButt.setText(_translate("MainWindow", "Latest"))
        self.latestStartButt.setText(_translate("MainWindow", "Latest Start"))
        self.shortestDayButt.setText(_translate("MainWindow", "Shortest Day"))
        self.gapsButt.setText(_translate("MainWindow", "Least Gaps"))
        self.cannotFindLabel.setText(_translate("MainWindow", "Cannot find:"))
        self.advancedSearchButton.setText(_translate("MainWindow", "Advanced Search"))
        self.scheduleMakerButton.setText(_translate("MainWindow", "Schedule Maker"))
        self.label.setText(_translate("MainWindow", "BYU Class Scheduling & Search Tool\n"
"\n"
"version - 0.0.0\n"
"\n"
"Josh Bedwell"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
