# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'search_page.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 700)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.picklesButton = QtWidgets.QPushButton(self.centralwidget)
        self.picklesButton.setGeometry(QtCore.QRect(20, 10, 111, 31))
        self.picklesButton.setObjectName("picklesButton")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 50, 171, 621))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.searchCol = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.searchCol.setContentsMargins(0, 0, 0, 0)
        self.searchCol.setObjectName("searchCol")
        self.deptLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.deptLabel.setObjectName("deptLabel")
        self.searchCol.addWidget(self.deptLabel)
        self.deptLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.deptLineEdit.setObjectName("deptLineEdit")
        self.searchCol.addWidget(self.deptLineEdit)
        self.courseNumLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.courseNumLabel.setObjectName("courseNumLabel")
        self.searchCol.addWidget(self.courseNumLabel)
        self.courseNumLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.courseNumLineEdit.setObjectName("courseNumLineEdit")
        self.searchCol.addWidget(self.courseNumLineEdit)
        self.courseNameLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.courseNameLabel.setObjectName("courseNameLabel")
        self.searchCol.addWidget(self.courseNameLabel)
        self.courseNameLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.courseNameLineEdit.setObjectName("courseNameLineEdit")
        self.searchCol.addWidget(self.courseNameLineEdit)
        self.instructorLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.instructorLabel.setObjectName("instructorLabel")
        self.searchCol.addWidget(self.instructorLabel)
        self.instructorLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.instructorLineEdit.setObjectName("instructorLineEdit")
        self.searchCol.addWidget(self.instructorLineEdit)
        self.courseTypeLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.courseTypeLabel.setObjectName("courseTypeLabel")
        self.searchCol.addWidget(self.courseTypeLabel)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.dayCheckbox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.dayCheckbox.setObjectName("dayCheckbox")
        self.verticalLayout_2.addWidget(self.dayCheckbox)
        self.eveningCheckbox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.eveningCheckbox.setObjectName("eveningCheckbox")
        self.verticalLayout_2.addWidget(self.eveningCheckbox)
        self.otherCheckbox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.otherCheckbox.setObjectName("otherCheckbox")
        self.verticalLayout_2.addWidget(self.otherCheckbox)
        self.searchCol.addLayout(self.verticalLayout_2)
        self.dayLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.dayLabel.setObjectName("dayLabel")
        self.searchCol.addWidget(self.dayLabel)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.mondayBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.mondayBox.setObjectName("mondayBox")
        self.verticalLayout_3.addWidget(self.mondayBox)
        self.wednesdayBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.wednesdayBox.setObjectName("wednesdayBox")
        self.verticalLayout_3.addWidget(self.wednesdayBox)
        self.fridayBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.fridayBox.setObjectName("fridayBox")
        self.verticalLayout_3.addWidget(self.fridayBox)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tuesdayBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.tuesdayBox.setObjectName("tuesdayBox")
        self.verticalLayout_4.addWidget(self.tuesdayBox)
        self.thursdayBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.thursdayBox.setObjectName("thursdayBox")
        self.verticalLayout_4.addWidget(self.thursdayBox)
        self.saturdayBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.saturdayBox.setObjectName("saturdayBox")
        self.verticalLayout_4.addWidget(self.saturdayBox)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.searchCol.addLayout(self.horizontalLayout)
        self.creditsLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.creditsLabel.setObjectName("creditsLabel")
        self.searchCol.addWidget(self.creditsLabel)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.maxCredits = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.maxCredits.setObjectName("maxCredits")
        self.horizontalLayout_2.addWidget(self.maxCredits)
        self.minCredits = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.minCredits.setObjectName("minCredits")
        self.horizontalLayout_2.addWidget(self.minCredits)
        self.searchCol.addLayout(self.horizontalLayout_2)
        self.courseLevelLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.courseLevelLabel.setObjectName("courseLevelLabel")
        self.searchCol.addWidget(self.courseLevelLabel)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.level100 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.level100.setObjectName("level100")
        self.verticalLayout_5.addWidget(self.level100)
        self.level200 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.level200.setObjectName("level200")
        self.verticalLayout_5.addWidget(self.level200)
        self.level300 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.level300.setObjectName("level300")
        self.verticalLayout_5.addWidget(self.level300)
        self.level400 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.level400.setObjectName("level400")
        self.verticalLayout_5.addWidget(self.level400)
        self.horizontalLayout_3.addLayout(self.verticalLayout_5)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.level500 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.level500.setObjectName("level500")
        self.verticalLayout_7.addWidget(self.level500)
        self.level600 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.level600.setObjectName("level600")
        self.verticalLayout_7.addWidget(self.level600)
        self.level700 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.level700.setObjectName("level700")
        self.verticalLayout_7.addWidget(self.level700)
        self.horizontalLayout_3.addLayout(self.verticalLayout_7)
        self.searchCol.addLayout(self.horizontalLayout_3)
        self.semesterDisplay = QtWidgets.QTextBrowser(self.centralwidget)
        self.semesterDisplay.setGeometry(QtCore.QRect(220, 10, 281, 31))
        self.semesterDisplay.setObjectName("semesterDisplay")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(220, 50, 751, 621))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Advanced Search"))
        self.picklesButton.setText(_translate("MainWindow", "Choose Semester"))
        self.deptLabel.setText(_translate("MainWindow", "Dept."))
        self.courseNumLabel.setText(_translate("MainWindow", "Course Num."))
        self.courseNameLabel.setText(_translate("MainWindow", "Course Name"))
        self.instructorLabel.setText(_translate("MainWindow", "Instructor"))
        self.courseTypeLabel.setText(_translate("MainWindow", "Type"))
        self.dayCheckbox.setText(_translate("MainWindow", "DAY"))
        self.eveningCheckbox.setText(_translate("MainWindow", "EVENING"))
        self.otherCheckbox.setText(_translate("MainWindow", "Something?"))
        self.dayLabel.setText(_translate("MainWindow", "Day"))
        self.mondayBox.setText(_translate("MainWindow", "Monday"))
        self.wednesdayBox.setText(_translate("MainWindow", "Wednesday"))
        self.fridayBox.setText(_translate("MainWindow", "Friday"))
        self.tuesdayBox.setText(_translate("MainWindow", "Tuesday"))
        self.thursdayBox.setText(_translate("MainWindow", "Thursday"))
        self.saturdayBox.setText(_translate("MainWindow", "Saturday"))
        self.creditsLabel.setText(_translate("MainWindow", "Credits (Max - Min)"))
        self.courseLevelLabel.setText(_translate("MainWindow", "Course Level"))
        self.level100.setText(_translate("MainWindow", "100"))
        self.level200.setText(_translate("MainWindow", "200"))
        self.level300.setText(_translate("MainWindow", "300"))
        self.level400.setText(_translate("MainWindow", "400"))
        self.level500.setText(_translate("MainWindow", "500"))
        self.level600.setText(_translate("MainWindow", "600"))
        self.level700.setText(_translate("MainWindow", "700"))
        self.semesterDisplay.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Would like to put the semester info here?</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
